import { AuditResult, BrandInfo, LeadInfo } from "../types";

export const generateEmailSubject = (brand: BrandInfo, result: AuditResult) => {
  return `BRAND SCORE - ${brand.name}`;
};

export const generateEmailHtml = (lead: LeadInfo, brand: BrandInfo, result: AuditResult, reportLink: string) => {
  const score = result.momentumScore;
  // Dynamic color for the score
  const scoreColor = score >= 80 ? "#000000" : score >= 60 ? "#555555" : "#000000";
  
  return `
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Zouhall Brand Score</title>
<style>
  body { font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; background-color: #f4f4f5; margin: 0; padding: 0; color: #111111; -webkit-font-smoothing: antialiased; }
  .container { max-width: 500px; margin: 40px auto; background-color: #ffffff; padding: 0; border: 1px solid #e4e4e7; }
  .header { background-color: #000000; padding: 30px 40px; text-align: center; }
  .logo { color: #ffffff; font-weight: 900; font-size: 20px; letter-spacing: 2px; text-transform: uppercase; text-decoration: none; }
  .content { padding: 40px; }
  .greeting { font-size: 16px; margin-bottom: 20px; color: #333; }
  .score-section { text-align: center; margin: 30px 0; border: 1px solid #f4f4f5; padding: 20px; background-color: #fafafa; }
  .score-val { font-size: 64px; font-weight: 800; line-height: 1; color: ${scoreColor}; letter-spacing: -2px; }
  .score-label { font-size: 11px; text-transform: uppercase; letter-spacing: 2px; color: #71717a; margin-top: 10px; }
  .summary { line-height: 1.6; font-size: 14px; margin-bottom: 30px; color: #52525b; border-left: 2px solid #000; padding-left: 15px; }
  .btn-container { text-align: center; margin-top: 40px; margin-bottom: 20px; }
  .btn { display: inline-block; background-color: #000000; color: #ffffff; padding: 18px 36px; text-decoration: none; font-weight: bold; text-transform: uppercase; letter-spacing: 1px; font-size: 12px; }
  .footer { background-color: #f4f4f5; padding: 20px; text-align: center; font-size: 10px; color: #a1a1aa; text-transform: uppercase; letter-spacing: 1px; }
  a { color: #000; text-decoration: underline; }
</style>
</head>
<body>
  <div class="container">
    <div class="header">
      <span class="logo">Zouhall</span>
    </div>
    
    <div class="content">
      <p class="greeting">Hi ${lead.firstName},</p>
      
      <p style="font-size: 14px; line-height: 1.5; color: #333;">
        The forensic audit for <strong>${brand.name}</strong> is complete. 
        We have analyzed your technical infrastructure and growth strategy.
      </p>
      
      <div class="score-section">
        <div class="score-val">${score}</div>
        <div class="score-label">Brand Momentum Score</div>
      </div>
      
      <div class="summary">
        <strong>Executive Summary:</strong><br/><br/>
        ${result.executiveSummary}
      </div>
      
      <p style="font-size: 14px; line-height: 1.5; color: #333;">
        Your detailed report includes a breakdown of 6 key business areas and a specific list of detected bottlenecks.
      </p>
      
      <div class="btn-container">
        <a href="${reportLink}" class="btn">View Full Report</a>
      </div>
    </div>
    
    <div class="footer">
      Generated by Zouhall Intelligence Engine<br/>
      Secure Report ID: ${reportLink.split('id=')[1]?.slice(0, 8) || 'Unknown'}
    </div>
  </div>
</body>
</html>
  `;
};